server:
  port: 8081
spring:
  profiles:
    active: test

---
server:
  port: 8082
spring:
  profiles: dev

---
server:
  port: 8083
spring:
  profiles: test

person:
  name: xx
  age: 3
  happy: false
  birth: 2021/10/10
  maps: {k1: v1, k2: v2}
  list:
    - code
    - music
    - girl
  dog:
    name: 旺财
    age: 5


